INSERT INTO Permissions (PermissionCode, PermissionName, Description, ModuleName, ActionType)
SELECT nuevos.PermissionCode, nuevos.PermissionName, nuevos.Description, nuevos.ModuleName, nuevos.ActionType
FROM (VALUES
('ACA_002','ACADEMICPROCESSES_SCHEDULETYPES_TAB','PERMITE VER LA PESTAÑA DE JORNADAS DE ESTUDIO.','ACADEMICPROCESSES','TAB'),
('ACA_003','ACADEMICPROCESSES_SCHEDULETYPES_CREATE','PERMITE CREAR JORNADAS DE ESTUDIO.','ACADEMICPROCESSES','CREATE'),
('ACA_004','ACADEMICPROCESSES_SCHEDULETYPES_UPDATE','PERMITE EDITAR JORNADAS DE ESTUDIO.','ACADEMICPROCESSES','UPDATE'),
('ACA_005','ACADEMICPROCESSES_SCHEDULETYPES_INACTIVE','PERMITE ACTIVAR/INACTIVAR JORNADAS DE ESTUDIO.','ACADEMICPROCESSES','INACTIVE')
) AS nuevos(PermissionCode, PermissionName, Description, ModuleName, ActionType)
WHERE NOT EXISTS (SELECT 1 FROM Permissions p WHERE p.PermissionCode = nuevos.PermissionCode)