INSERT INTO Permissions (PermissionCode, PermissionName, Description, ModuleName, ActionType)
SELECT * FROM (VALUES
('ACP_001', 'ACADEMICPROCESSES_CAREERPROGRAM_CREATE', 'PERMITE REGISTRAR NUEVAS CARRERAS EN EL SISTEMA.', 'ACADEMICPROCESSES', 'CREATE'),
('ACP_002', 'ACADEMICPROCESSES_CAREERPROGRAM_UPDATE', 'PERMITE MODIFICAR CARRERAS EN EL SISTEMA.', 'ACADEMICPROCESSES', 'UPDATE'),
('ACP_003', 'ACADEMICPROCESSES_CAREERPROGRAM_INACTIVE', 'PERMITE ACTIVAR/DESACTIVAR CARRERAS EN EL SISTEMA.', 'ACADEMICPROCESSES', 'INACTIVE'),
('ACP_004', 'ACADEMICPROCESSES_CAREERPROGRAM_IMPORT', 'PERMITE IMPORTAR LISTADOS DE CARRERAS EN EL SISTEMA.', 'ACADEMICPROCESSES', 'IMPORT')
) AS nuevos(PermissionCode, PermissionName, Description, ModuleName, ActionType)
WHERE NOT EXISTS (SELECT 1 FROM Permissions p WHERE p.PermissionCode = nuevos.PermissionCode)