INSERT INTO Permissions (PermissionCode, PermissionName, Description, ModuleName, ActionType)
SELECT * FROM (VALUES 


-- ==================================================== INVENTORY ============================================================================
('KDX_001', 'KARDEX_TAB', 'PERMITE VISUALIZAR EL BOTÓN PRINCIPAL EN EL MENÚ PARA KARDEX EN EL SISTEMA.', 'KARDEX', 'TAB'),

-- KARDEX MODULO CATALOG ITEMS KARDEX
('KDX_002', 'KARDEX_CATALOG', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE DE ITEMS EN EL SISTEMA.', 'KARDEX', 'TAB'),

('KDX_003', 'KARDEX_CATALOG_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE DE ITEMS EN EL SISTEMA.', 'KARDEX', 'CREATE'),

('KDX_004', 'KARDEX_CATALOG_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE DE ITEMS EN EL SISTEMA.', 'KARDEX', 'READ'),

('KDX_005', 'KARDEX_CATALOG_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE DE ITEMS EN EL SISTEMA.', 'KARDEX', 'UPDATE'),

('KDX_006', 'KARDEX_CATALOG_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE DE ITEMS EN EL SISTEMA.', 'KARDEX', 'INACTIVE'),

('KDX_007', 'KARDEX_CATALOG_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE DE ITEMS EN EL SISTEMA.', 'KARDEX', 'EXPORT'),

('KDX_008', 'KARDEX_CATALOG_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE DE ITEMS EN EL SISTEMA.', 'KARDEX', 'IMPORT'),

-- KARDEX MODULO INVENTARIO 

('KDX_009', 'KARDEX_INVENTORY', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE INVENTARIOS EN EL SISTEMA.', 'KARDEX', 'TAB'),

('KDX_010', 'KARDEX_INVENTORY_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE INVENTARIOS EN EL SISTEMA.', 'KARDEX', 'CREATE'),

('KDX_011', 'KARDEX_INVENTORY_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE INVENTARIOS EN EL SISTEMA.', 'KARDEX', 'READ'),

('KDX_012', 'KARDEX_INVENTORY_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE INVENTARIOS EN EL SISTEMA.', 'KARDEX', 'UPDATE'),

('KDX_013', 'KARDEX_INVENTORY_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE INVENTARIOS EN EL SISTEMA.', 'KARDEX', 'INACTIVE'),

('KDX_014', 'KARDEX_INVENTORY_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE INVENTARIOS EN EL SISTEMA.', 'KARDEX', 'EXPORT'),

('KDX_015', 'KARDEX_INVENTORY_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE INVENTARIOS EN EL SISTEMA.', 'KARDEX', 'IMPORT'),

-- KARDEX MODULO COST VALUATION 

('KDX_016', 'KARDEX_COSTVALUATION', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA VALORIZACIÓN DE COSTOS EN EL SISTEMA.', 'KARDEX', 'TAB'),

('KDX_017', 'KARDEX_COSTVALUATION_CREATE', 'PERMITE REGISTRAR NUEVA VALORIZACIÓN DE COSTOS EN EL SISTEMA.', 'KARDEX', 'CREATE'),

('KDX_018', 'KARDEX_COSTVALUATION_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE VALORIZACIÓN DE COSTOS EN EL SISTEMA.', 'KARDEX', 'READ'),

('KDX_019', 'KARDEX_COSTVALUATION_UPDATE', 'PERMITE MODIFICAR VALORIZACIÓN DE COSTOS EN EL SISTEMA.', 'KARDEX', 'UPDATE'),

('KDX_020', 'KARDEX_COSTVALUATION_INACTIVE', 'PERMITE DESACTIVAR VALORIZACIÓN DE COSTOS EN EL SISTEMA.', 'KARDEX', 'INACTIVE'),

('KDX_021', 'KARDEX_COSTVALUATION_EXPORT', 'PERMITE EXPORTAR LISTADO DE VALORIZACIÓN DE COSTOS EN EL SISTEMA.', 'KARDEX', 'EXPORT'),

('KDX_022', 'KARDEX_COSTVALUATION_IMPORT', 'PERMITE IMPORTAR LISTADOS DE VALORIZACIÓN DE COSTOS EN EL SISTEMA.', 'KARDEX', 'IMPORT'),

-- KARDEX MODULO INPUT CONTROL

('KDX_023', 'KARDEX_INPUTCONTROL', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA CONTROL DE INSUMOS EN EL SISTEMA.', 'KARDEX', 'TAB'),

('KDX_024', 'KARDEX_INPUTCONTROL_CREATE', 'PERMITE REGISTRAR NUEVA CONTROL DE INSUMOS EN EL SISTEMA.', 'KARDEX', 'CREATE'),

('KDX_025', 'KARDEX_INPUTCONTROL_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE CONTROL DE INSUMOS EN EL SISTEMA.', 'KARDEX', 'READ'),

('KDX_026', 'KARDEX_INPUTCONTROL_UPDATE', 'PERMITE MODIFICAR CONTROL DE INSUMOS EN EL SISTEMA.', 'KARDEX', 'UPDATE'),

('KDX_027', 'KARDEX_INPUTCONTROL_INACTIVE', 'PERMITE DESACTIVAR CONTROL DE INSUMOS EN EL SISTEMA.', 'KARDEX', 'INACTIVE'),

('KDX_028', 'KARDEX_INPUTCONTROL_EXPORT', 'PERMITE EXPORTAR LISTADO DE CONTROL DE INSUMOS EN EL SISTEMA.', 'KARDEX', 'EXPORT'),

('KDX_029', 'KARDEX_INPUTCONTROL_IMPORT', 'PERMITE IMPORTAR LISTADOS DE CONTROL DE INSUMOS EN EL SISTEMA.', 'KARDEX', 'IMPORT'),

-- KARDEX MODULO REPORTS

('KDX_030', 'KARDEX_REPORTS', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA REPORTERÍA EN EL SISTEMA.', 'KARDEX', 'TAB'),

('KDX_031', 'KARDEX_REPORTS_CREATE', 'PERMITE REGISTRAR NUEVA REPORTERÍA EN EL SISTEMA.', 'KARDEX', 'CREATE'),

('KDX_032', 'KARDEX_REPORTS_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE REPORTERÍA EN EL SISTEMA.', 'KARDEX', 'READ'),

('KDX_033', 'KARDEX_REPORTS_UPDATE', 'PERMITE MODIFICAR REPORTERÍA EN EL SISTEMA.', 'KARDEX', 'UPDATE'),

('KDX_034', 'KARDEX_REPORTS_INACTIVE', 'PERMITE DESACTIVAR REPORTERÍA EN EL SISTEMA.', 'KARDEX', 'INACTIVE'),

('KDX_035', 'KARDEX_REPORTS_EXPORT', 'PERMITE EXPORTAR LISTADO DE REPORTERÍA EN EL SISTEMA.', 'KARDEX', 'EXPORT'),

('KDX_036', 'KARDEX_REPORTS_IMPORT', 'PERMITE IMPORTAR LISTADOS DE REPORTERÍA EN EL SISTEMA.', 'KARDEX', 'IMPORT'),


-- ==================================================== STATIC ITEMS LEGACY ============================================================================
('STC_001', 'STATICITEMS_TAB', 'PERMITE VISUALIZAR EL BOTÓN PRINCIPAL EN EL MENÚ PARA STATICITEMS EN EL SISTEMA.', 'STATICITEMS', 'TAB'),

-- STATIC ITEMS MENU MANAGMENT
('STC_002', 'STATICITEMS_MANAGMENT', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'TAB'),

('STC_003', 'STATICITEMS_MANAGMENT_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'CREATE'),

('STC_004', 'STATICITEMS_MANAGMENT_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'READ'),

('STC_005', 'STATICITEMS_MANAGMENT_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'UPDATE'),

('STC_006', 'STATICITEMS_MANAGMENT_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'INACTIVE'),

('STC_007', 'STATICITEMS_MANAGMENT_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'EXPORT'),

('STC_008', 'STATICITEMS_MANAGMENT_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'IMPORT'),

-- STATIC ITEMS MENU RESPONSLETTER (RESPONSABILITY LETTER)
('STC_009', 'STATICITEMS_RESPONSLETTER', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE CARTA DE RESPONSABILIDAD DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'TAB'),

('STC_010', 'STATICITEMS_RESPONSLETTER_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE CARTA DE RESPONSABILIDAD DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'CREATE'),

('STC_011', 'STATICITEMS_RESPONSLETTER_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE CARTA DE RESPONSABILIDAD DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'READ'),

('STC_012', 'STATICITEMS_RESPONSLETTER_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE CARTA DE RESPONSABILIDAD DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'UPDATE'),

('STC_013', 'STATICITEMS_RESPONSLETTER_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE CARTA DE RESPONSABILIDAD DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'INACTIVE'),

('STC_014', 'STATICITEMS_RESPONSLETTER_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE CARTA DE RESPONSABILIDAD DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'EXPORT'),

('STC_015', 'STATICITEMS_RESPONSLETTER_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE CARTA DE RESPONSABILIDAD DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'IMPORT'),

-- STATIC ITEMS MENU MOVEMENTS
('STC_016', 'STATICITEMS_MOVEMENTS', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE CONTROL DE MOVIMIENTOS DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'TAB'),

('STC_017', 'STATICITEMS_MOVEMENTS_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE CONTROL DE MOVIMIENTOS DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'CREATE'),

('STC_018', 'STATICITEMS_MOVEMENTS_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE CONTROL DE MOVIMIENTOS DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'READ'),

('STC_019', 'STATICITEMS_MOVEMENTS_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE CONTROL DE MOVIMIENTOS DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'UPDATE'),

('STC_020', 'STATICITEMS_MOVEMENTS_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE CONTROL DE MOVIMIENTOS DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'INACTIVE'),

('STC_021', 'STATICITEMS_MOVEMENTS_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE CONTROL DE MOVIMIENTOS DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'EXPORT'),

('STC_022', 'STATICITEMS_MOVEMENTS_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE CONTROL DE MOVIMIENTOS DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'IMPORT'),

-- STATIC ITEMS MENU MAINTENANCE
('STC_023', 'STATICITEMS_MAINTENANCE', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE MANTENIMIENTO Y SOPORTE DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'TAB'),

('STC_024', 'STATICITEMS_MAINTENANCE_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE MANTENIMIENTO Y SOPORTE DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'CREATE'),

('STC_025', 'STATICITEMS_MAINTENANCE_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE MANTENIMIENTO Y SOPORTE DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'READ'),

('STC_026', 'STATICITEMS_MAINTENANCE_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE MANTENIMIENTO Y SOPORTE DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'UPDATE'),

('STC_027', 'STATICITEMS_MAINTENANCE_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE MANTENIMIENTO Y SOPORTE DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'INACTIVE'),

('STC_028', 'STATICITEMS_MAINTENANCE_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE MANTENIMIENTO Y SOPORTE DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'EXPORT'),

('STC_029', 'STATICITEMS_MAINTENANCE_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE MANTENIMIENTO Y SOPORTE DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'IMPORT'),

-- STATIC ITEMS MENU DEPRECIATION Y VALUATION
('STC_030', 'STATICITEMS_DEPRECIATION', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE DEPRECIACIÓN Y VALUACIÓN DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'TAB'),

('STC_031', 'STATICITEMS_DEPRECIATION_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE DEPRECIACIÓN Y VALUACIÓN DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'CREATE'),

('STC_032', 'STATICITEMS_DEPRECIATION_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE DEPRECIACIÓN Y VALUACIÓN DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'READ'),

('STC_033', 'STATICITEMS_DEPRECIATION_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE DEPRECIACIÓN Y VALUACIÓN DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'UPDATE'),

('STC_034', 'STATICITEMS_DEPRECIATION_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE DEPRECIACIÓN Y VALUACIÓN DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'INACTIVE'),

('STC_035', 'STATICITEMS_DEPRECIATION_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE DEPRECIACIÓN Y VALUACIÓN DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'EXPORT'),

('STC_036', 'STATICITEMS_DEPRECIATION_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE DEPRECIACIÓN Y VALUACIÓN DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'IMPORT'),

-- STATIC ITEMS MENU REPORTS
('STC_037', 'STATICITEMS_REPORTS', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE REPORTES DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'TAB'),

('STC_038', 'STATICITEMS_REPORTS_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE REPORTES DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'CREATE'),

('STC_039', 'STATICITEMS_REPORTS_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE REPORTES DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'READ'),

('STC_040', 'STATICITEMS_REPORTS_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE REPORTES DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'UPDATE'),

('STC_041', 'STATICITEMS_REPORTS_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE REPORTES DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'INACTIVE'),

('STC_042', 'STATICITEMS_REPORTS_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE REPORTES DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'EXPORT'),

('STC_043', 'STATICITEMS_REPORTS_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE REPORTES DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'IMPORT'),

-- STATIC ITEMS MENU CONFIGURATION
('STC_044', 'STATICITEMS_CONFIGURATION', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE CONFIGURACIÓN DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'TAB'),

('STC_045', 'STATICITEMS_CONFIGURATION_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE CONFIGURACIÓN DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'CREATE'),

('STC_046', 'STATICITEMS_CONFIGURATION_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE CONFIGURACIÓN DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'READ'),

('STC_047', 'STATICITEMS_CONFIGURATION_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE CONFIGURACIÓN DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'UPDATE'),

('STC_048', 'STATICITEMS_CONFIGURATION_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE CONFIGURACIÓN DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'INACTIVE'),

('STC_049', 'STATICITEMS_CONFIGURATION_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE CONFIGURACIÓN DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'EXPORT'),

('STC_050', 'STATICITEMS_CONFIGURATION_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE CONFIGURACIÓN DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'IMPORT'),

-- ==================================================== KARDEX ============================================================================

--KARDEX MODULO CATALOG LOCATIONS CATEGORIES
('KDX_037', 'KARDEX_CATLOCATION', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ.', 'KARDEX', 'TAB'),

('KDX_038', 'KARDEX_CATLOCATION_CREATE', 'PERMITE REGISTRAR NUEVA REPORTERÍA EN EL SISTEMA.', 'KARDEX', 'CREATE'),

('KDX_039', 'KARDEX_CATLOCATION_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE REPORTERÍA EN EL SISTEMA.', 'KARDEX', 'READ'),

('KDX_040', 'KARDEX_CATLOCATION_UPDATE', 'PERMITE MODIFICAR REPORTERÍA EN EL SISTEMA.', 'KARDEX', 'UPDATE'),

('KDX_041', 'KARDEX_CATLOCATION_INACTIVE', 'PERMITE DESACTIVAR REPORTERÍA EN EL SISTEMA.', 'KARDEX', 'INACTIVE'),

('KDX_042', 'KARDEX_CATLOCATION_EXPORT', 'PERMITE EXPORTAR LISTADO DE REPORTERÍA EN EL SISTEMA.', 'KARDEX', 'EXPORT'),

('KDX_043', 'KARDEX_CATLOCATION_IMPORT', 'PERMITE IMPORTAR LISTADOS DE REPORTERÍA EN EL SISTEMA.', 'KARDEX', 'IMPORT'),

('KDX_049', 'KARDEX_INVENTORY_TEMPLATE', 'PERMISO PARA UTILIZAR LA PLANTILLA DE BODEGAS AL USUARIO ENCARGADO DE INVENTARIOS.', 'KARDEX', 'UPDATE'),

--MODULO DE ACTIVOS FIJOS

('FA_001', 'FA_CATEGORIES', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ.', 'FIXEDASSETS', 'TAB'),

('FA_002', 'FA_CATEGORIES_CREATE', 'PERMITE REGISTRAR NUEVA REPORTERÍA EN EL SISTEMA.', 'FIXEDASSETS', 'CREATE'),

('FA_003', 'FA_CATEGORIES_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE REPORTERÍA EN EL SISTEMA.', 'FIXEDASSETS', 'READ'),

('FA_004', 'FA_CATEGORIES_UPDATE', 'PERMITE MODIFICAR REPORTERÍA EN EL SISTEMA.', 'FIXEDASSETS', 'UPDATE'),

('FA_005', 'FA_CATEGORIES_INACTIVE', 'PERMITE DESACTIVAR REPORTERÍA EN EL SISTEMA.', 'FIXEDASSETS', 'INACTIVE'),

('FA_006', 'FA_CATEGORIES_EXPORT', 'PERMITE EXPORTAR LISTADO DE REPORTERÍA EN EL SISTEMA.', 'FIXEDASSETS', 'EXPORT'),

('FA_007', 'FA_ATTRIBUTES_CREATE', 'PERMITE REGISTRAR NUEVA REPORTERÍA EN EL SISTEMA.', 'FIXEDASSETS', 'CREATE'),

('FA_008', 'FA_ATTRIBUTES_UPDATE', 'PERMITE MODIFICAR REPORTERÍA EN EL SISTEMA.', 'FIXEDASSETS', 'UPDATE'),

('FA_009', 'FA_ATTRIBUTES_INACTIVE', 'PERMITE DESACTIVAR REPORTERÍA EN EL SISTEMA.', 'FIXEDASSETS', 'INACTIVE'),

('FA_010', 'FA_ASSETS_CREATE', 'PERMITE REGISTRAR NUEVA REPORTERÍA EN EL SISTEMA', 'FIXEDASSETS', 'CREATE'),

('FA_011', 'FA_ASSETS_UPDATE', 'PERMITE MODIFICAR REPORTERÍA EN EL SISTEMA.', 'FIXEDASSETS', 'UPDATE'),

('FA_012', 'FA_ASSETS_INACTIVE', 'PERMITE DESACTIVAR REPORTERÍA EN EL SISTEMA.', 'FIXEDASSETS', 'INACTIVE'),

('FA_013', 'FA_ASSETS_EXPORT', 'PERMITE EXPORTAR LISTADO DE REPORTERÍA EN EL SISTEMA.', 'FIXEDASSETS', 'EXPORT'),

('FA_014', 'FA_ASSETS_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE REPORTERÍA EN EL SISTEMA.', 'FIXEDASSETS', 'READ'),

('FA_015', 'FA_MOVEMENTS_CREATE', 'PERMITE REGISTRAR TRASLADOS EN EL SISTEMA', 'FIXEDASSETS', 'CREATE'),

('FA_016', 'FA_MOVEMENTS_UPDATE', 'PERMITE MODIFICAR TRASLADOS EN EL SISTEMA.', 'FIXEDASSETS', 'UPDATE'),

('FA_017', 'FA_MOVEMENTS_INACTIVE', 'PERMITE DESACTIVAR TRASLADOS EN EL SISTEMA.', 'FIXEDASSETS', 'INACTIVE'),

('FA_018', 'FA_MOVEMENTS_EXPORT', 'PERMITE EXPORTAR LISTADO DE TRASLADOS EN EL SISTEMA.', 'FIXEDASSETS', 'EXPORT'),

('FA_019', 'FA_MOVEMENTS_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE TRASLADOS EN EL SISTEMA.', 'FIXEDASSETS', 'READ'),

('FA_020', 'FA_MOVEMENTSSTATES_CREATE', 'PERMITE REGISTRAR ESTADOS DE TRASLADOS EN EL SISTEMA', 'FIXEDASSETS', 'CREATE'),

('FA_021', 'FA_MOVEMENTSSTATES_UPDATE', 'PERMITE MODIFICAR ESTADOS DE TRASLADOS EN EL SISTEMA.', 'FIXEDASSETS', 'UPDATE'),

('FA_022', 'FA_MOVEMENTSSTATES_INACTIVE', 'PERMITE DESACTIVAR ESTADOS DE TRASLADOS EN EL SISTEMA.', 'FIXEDASSETS', 'INACTIVE'),

('FA_023', 'FA_MOVEMENTSSTATES_EXPORT', 'PERMITE EXPORTAR LISTADO DE ESTADOS DE TRASLADOS EN EL SISTEMA.', 'FIXEDASSETS', 'EXPORT'),

('FA_024', 'FA_MOVEMENTSSTATES_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE ESTADOS TRASLADOS EN EL SISTEMA.', 'FIXEDASSETS', 'READ'),

('FA_025', 'FA_MOVEMENTSTRANSITION_CREATE', 'PERMITE REGISTRAR TRANSICIONES DE ESTADOS DE TRASLADOS EN EL SISTEMA', 'FIXEDASSETS', 'CREATE'),

('FA_026', 'FA_MOVEMENTSTRANSITION_UPDATE', 'PERMITE MODIFICAR TRANSICIONES DE ESTADOS DE TRASLADOS EN EL SISTEMA.', 'FIXEDASSETS', 'UPDATE'),

('FA_027', 'FA_MOVEMENTSTRANSITION_INACTIVE', 'PERMITE DESACTIVAR TRANSICIONES DE ESTADOS DE TRASLADOS EN EL SISTEMA.', 'FIXEDASSETS', 'INACTIVE'),

('FA_028', 'FA_MOVEMENTSTRANSITION_EXPORT', 'PERMITE EXPORTAR LISTADO DE TRANSICIONES DE ESTADOS DE TRASLADOS EN EL SISTEMA.', 'FIXEDASSETS', 'EXPORT'),

('FA_029', 'FA_MOVEMENTSTRANSITION_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE TRANSICIONES DE ESTADOS TRASLADOS EN EL SISTEMA.', 'FIXEDASSETS', 'READ'),

('FA_030', 'FA_ASSETS_DELETE', 'PERMITE ELIMINAR COMPLETAMENTE UN REGISTRO EN EL SISTEMA.', 'FIXEDASSETS', 'DELETE'),


--MODULO DE ACTIVOS FIJOS PARA TECNOLOGIA
('FA_031', 'FA_ITMS_TECH', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ.', 'FIXEDASSETS', 'TAB'),

('FA_032', 'FA_ITMS_TECH_CREATE', 'PERMITE REGISTRAR NUEVA REPORTERÍA EN EL SISTEMA.', 'FIXEDASSETS', 'CREATE'),

('FA_033', 'FA_ITMS_TECH_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE REPORTERÍA EN EL SISTEMA.', 'FIXEDASSETS', 'READ'),

('FA_034', 'FA_ITMS_TECH_UPDATE', 'PERMITE MODIFICAR REPORTERÍA EN EL SISTEMA.', 'FIXEDASSETS', 'UPDATE'),

('FA_035', 'FA_ITMS_TECH_INACTIVE', 'PERMITE DESACTIVAR REPORTERÍA EN EL SISTEMA.', 'FIXEDASSETS', 'INACTIVE'),

('FA_036', 'FA_ITMS_TECH_EXPORT', 'PERMITE EXPORTAR LISTADO DE REPORTERÍA EN EL SISTEMA.', 'FIXEDASSETS', 'EXPORT'),

('FA_037', 'FA_ITMS_TECH_PRINT', 'PERMITE QUE EL USUARI PUEDA IMPRIMIR EL REPORTE CONSULTADO.', 'FIXEDASSETS', 'PRINT'),

('FA_038', 'FA_ITMS_TECH_MANAGEMENT', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ.', 'FIXEDASSETS', 'TAB'),

('FA_039', 'FA_ITMS_TECH_MANAGEMENT_CREATE', 'PERMITE REGISTRAR NUEVA REPORTERÍA EN EL SISTEMA.', 'FIXEDASSETS', 'CREATE'),

('FA_040', 'FA_ITMS_TECH_MANAGEMENT_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE REPORTERÍA EN EL SISTEMA.', 'FIXEDASSETS', 'READ'),

('FA_041', 'FA_ITMS_TECH_MANAGEMENT_UPDATE', 'PERMITE MODIFICAR REPORTERÍA EN EL SISTEMA.', 'FIXEDASSETS', 'UPDATE'),

('FA_042', 'FA_ITMS_TECH_MANAGEMENT_INACTIVE', 'PERMITE DESACTIVAR REPORTERÍA EN EL SISTEMA.', 'FIXEDASSETS', 'INACTIVE'),

('FA_043', 'FA_ITMS_TECH_MANAGEMENT_EXPORT', 'PERMITE EXPORTAR LISTADO DE REPORTERÍA EN EL SISTEMA.', 'FIXEDASSETS', 'EXPORT'),

('FA_044', 'FA_ITMS_TECH_MANAGEMENT_PRINT', 'PERMITE QUE EL USUARI PUEDA IMPRIMIR EL REPORTE CONSULTADO.', 'FIXEDASSETS', 'PRINT'),

('FA_045', 'FA_ITMS_TECH_ROLES', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ.', 'FIXEDASSETS', 'TAB'),

('FA_046', 'FA_ITMS_TECH_ROLES_CREATE', 'PERMITE REGISTRAR NUEVA REPORTERÍA EN EL SISTEMA.', 'FIXEDASSETS', 'CREATE'),

('FA_047', 'FA_ITMS_TECH_ROLES_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE REPORTERÍA EN EL SISTEMA.', 'FIXEDASSETS', 'READ'),

('FA_048', 'FA_ITMS_TECH_ROLES_UPDATE', 'PERMITE MODIFICAR REPORTERÍA EN EL SISTEMA.', 'FIXEDASSETS', 'UPDATE'),

('FA_049', 'FA_ITMS_TECH_ROLES_INACTIVE', 'PERMITE DESACTIVAR REPORTERÍA EN EL SISTEMA.', 'FIXEDASSETS', 'INACTIVE'),

('FA_050', 'FA_ITMS_TECH_ROLES_EXPORT', 'PERMITE EXPORTAR LISTADO DE REPORTERÍA EN EL SISTEMA.', 'FIXEDASSETS', 'EXPORT'),

('FA_051', 'FA_ITMS_TECH_ROLES_PRINT', 'PERMITE QUE EL USUARIO PUEDA IMPRIMIR EL REPORTE CONSULTADO.', 'FIXEDASSETS', 'PRINT')

) AS nuevos(PermissionCode, PermissionName, Description, ModuleName, ActionType)
WHERE NOT EXISTS (SELECT 1 FROM Permissions p WHERE p.PermissionCode = nuevos.PermissionCode)